org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neoforge_version=21.1.235
neoforge_version_range=[21.1.235,)
loader_version_range=[4,)
ysm_version_range=[2.6.0-neoforge+mc1.21.1,)
epicfight_version=21.17.3.1-mc1.21.1-neoforge
epicfight_version_range=[21.17.3.1,21.18)
ysm_mapping_api_version=0.1.8
ysm_mapping_api_version_range=0.1.8
configured_version_range=[2.6.3,)
touhou_little_maid_version_range=[1.5,1.6)
epicfight_touhou_little_maid_version_range=[1.1,1.4)

mod_id=ysm_epicfight_compat
mod_name=YSM Epic Fight Compat
mod_license=MIT
mod_version=0.10.0
mod_group_id=net.okitsu.ysmepicfightcompat
mod_authors=sakuraimikoto33
mod_description=Renders official Yes Steve Model player models through Epic Fight combat animation meshes.
